# Generated by Django 5.2.5 on 2025-08-12 03:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=300, upload_to="uploader/", verbose_name="檔案物件"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="使用者下載檔案時，將顯示此名稱",
                        max_length=20,
                        verbose_name="名稱",
                    ),
                ),
                (
                    "mimetype",
                    models.CharField(max_length=255, verbose_name="MIME 類型"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上傳時間"),
                ),
                (
                    "require_login",
                    models.BooleanField(default=False, verbose_name="需登入才可存取"),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上傳者",
                    ),
                ),
            ],
            options={
                "verbose_name": "使用者檔案",
                "verbose_name_plural": "使用者檔案",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
