# Generated by Django 5.2.5 on 2025-08-12 07:10

import Uploader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uploader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="file",
            field=models.FileField(
                max_length=300,
                upload_to=Uploader.models.file_path,
                verbose_name="檔案物件",
            ),
        ),
    ]
