# Generated by Django 5.2.6 on 2025-09-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uploader", "0002_alter_userfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="password",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="密碼"
            ),
        ),
        migrations.AddField(
            model_name="userfile",
            name="require_password",
            field=models.BooleanField(default=False, verbose_name="需密碼才可存取"),
        ),
    ]
