# Generated by Django 6.0 on 2025-12-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uploader", "0004_mdimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="name",
            field=models.CharField(
                help_text="使用者下載檔案時，將顯示此名稱",
                max_length=100,
                verbose_name="名稱",
            ),
        ),
    ]
