# Generated by Django 5.2.5 on 2025-08-08 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='會議名稱')),
                ('start_time', models.DateTimeField(verbose_name='開始時間')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('description', models.TextField(blank=True, null=True, verbose_name='會議描述')),
                ('location', models.CharField(verbose_name='會議地點')),
                ('participants', models.ManyToManyField(related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='參與者')),
            ],
            options={
                'verbose_name': '會議',
                'verbose_name_plural': '會議',
            },
        ),
    ]
