# Generated by Django 5.2.5 on 2025-08-08 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmeeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='參與者'),
        ),
    ]
