# Generated by Django 5.2.5 on 2025-08-09 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetings', '0003_dmeeting_creator_dmeeting_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dmeeting',
            name='absent_members',
            field=models.ManyToManyField(blank=True, related_name='absent_meetings', to=settings.AUTH_USER_MODEL, verbose_name='請假成員'),
        ),
        migrations.AddField(
            model_name='dmeeting',
            name='can_absent',
            field=models.BooleanField(default=True, verbose_name='允許請假'),
        ),
        migrations.AlterField(
            model_name='dmeeting',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL, verbose_name='創建者'),
        ),
        migrations.AlterField(
            model_name='dmeeting',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='dmeeting',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL, verbose_name='主持人'),
        ),
        migrations.AlterField(
            model_name='dmeeting',
            name='location',
            field=models.CharField(verbose_name='地點'),
        ),
        migrations.AlterField(
            model_name='dmeeting',
            name='name',
            field=models.CharField(max_length=255, verbose_name='名稱'),
        ),
    ]
