# Generated by Django 5.2.5 on 2025-08-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetings', '0004_dmeeting_absent_members_dmeeting_can_absent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmeeting',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='說明'),
        ),
    ]
