# Generated by Django 5.2.5 on 2025-08-10 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetings', '0005_alter_dmeeting_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmeeting',
            name='absent_members',
        ),
        migrations.CreateModel(
            name='DAbsentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='請假事由')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '已批准'), ('rejected', '已拒絕')], default='pending', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_requests', to='Meetings.dmeeting', verbose_name='會議')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='成員')),
            ],
            options={
                'verbose_name': '假單',
                'verbose_name_plural': '假單',
            },
        ),
    ]
