# Generated by Django 5.2.5 on 2025-08-10 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Meetings", "0006_remove_dmeeting_absent_members_dabsentrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dabsentrequest",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="審核人",
            ),
        ),
    ]
