# Generated by Django 5.2.5 on 2025-08-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Meetings", "0007_dabsentrequest_reviewer"),
    ]

    operations = [
        migrations.AddField(
            model_name="dabsentrequest",
            name="reviewer_comment",
            field=models.TextField(blank=True, null=True, verbose_name="審核意見"),
        ),
    ]
