# Generated by Django 5.2.6 on 2025-09-06 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Meetings", "0008_dabsentrequest_reviewer_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dabsentrequest",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="審核人",
            ),
        ),
    ]
