# Generated by Django 5.2.6 on 2025-09-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Meetings", "0009_alter_dabsentrequest_reviewer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dmeeting",
            name="participants",
        ),
    ]
