# Generated by Django 5.2.6 on 2025-10-01 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Meetings", "0010_remove_dmeeting_participants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingSignIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="開放時間")),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="關閉時間"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sign_ins",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="創建者",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sign_ins",
                        to="Meetings.dmeeting",
                        verbose_name="會議",
                    ),
                ),
            ],
            options={
                "verbose_name": "會議簽到",
                "verbose_name_plural": "會議簽到",
            },
        ),
        migrations.CreateModel(
            name="SingInRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signed_in_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="簽到時間"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="成員",
                    ),
                ),
                (
                    "sign_in_method",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="Meetings.meetingsignin",
                        verbose_name="簽到中介",
                    ),
                ),
            ],
            options={
                "verbose_name": "簽到記錄",
                "verbose_name_plural": "簽到記錄",
            },
        ),
    ]
