# Generated by Django 5.2.7 on 2025-10-18 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Meetings", "0011_meetingsignin_singinrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="dmeeting",
            name="discord_notify_time",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(seconds=300),
                verbose_name="Discord 提前通知時間",
            ),
        ),
    ]
