# Generated by Django 5.2.7 on 2025-10-18 16:39

import Meetings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Meetings", "0012_dmeeting_discord_notify_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="dmeeting",
            name="discord_mentions",
            field=models.JSONField(
                blank=True,
                default=Meetings.models.everyone_mention,
                verbose_name="Discord 通知提及",
            ),
        ),
    ]
