# Generated by Django 5.2.7 on 2025-11-23 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Meetings", "0013_dmeeting_discord_mentions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dabsentrequest",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="absent_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="成員",
            ),
        ),
    ]
