# Generated by Django 5.2.6 on 2025-09-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="置頂"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="pinned_until",
            field=models.DateTimeField(blank=True, null=True, verbose_name="置頂直到"),
        ),
    ]
