# Generated by Django 5.2.6 on 2025-09-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0002_announcement_is_pinned_announcement_pinned_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="pinned_until",
            field=models.DateTimeField(blank=True, null=True, verbose_name="置頂期限"),
        ),
    ]
