# Generated by Django 5.2.6 on 2025-09-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Announcements", "0003_alter_announcement_pinned_until"),
    ]

    operations = [
        migrations.RenameField(
            model_name="announcement",
            old_name="pinned_until",
            new_name="pin_until",
        ),
    ]
