# Generated by Django 5.2.7 on 2025-10-30 09:05

import Auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logincode",
            name="code",
            field=models.CharField(
                default=Auth.models.generate_login_code,
                max_length=20,
                unique=True,
                verbose_name="代碼",
            ),
        ),
    ]
