# Generated by Django 5.2.5 on 2025-08-07 02:32

import Members.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dmember',
            managers=[
                ('objects', Members.models.DMemberManager()),
            ],
        ),
    ]
