# Generated by Django 5.2.5 on 2025-08-07 12:26

import Members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0004_dmember_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="dmember",
            name="avatar",
            field=models.ImageField(
                blank=True,
                max_length=256,
                null=True,
                upload_to=Members.models.user_avatar_path,
                verbose_name="頭像",
            ),
        ),
    ]
