# Generated by Django 5.2.5 on 2025-08-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0005_dmember_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dmember",
            name="avatar",
            field=models.URLField(blank=True, null=True, verbose_name="頭像"),
        ),
    ]
