# Generated by Django 5.2.5 on 2025-08-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0006_alter_dmember_avatar"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WarningHistory",
        ),
    ]
