# Generated by Django 5.2.5 on 2025-08-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0008_warninghistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="warninghistory",
            options={
                "ordering": ["-time"],
                "verbose_name": "記點歷史",
                "verbose_name_plural": "記點歷史",
            },
        ),
    ]
