# Generated by Django 5.2.5 on 2025-08-17 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0009_alter_warninghistory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warninghistory",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warning_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="成員",
            ),
        ),
        migrations.AlterField(
            model_name="warninghistory",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="附註"),
        ),
        migrations.AlterField(
            model_name="warninghistory",
            name="points",
            field=models.FloatField(default=0.0, verbose_name="點數"),
        ),
        migrations.AlterField(
            model_name="warninghistory",
            name="reason",
            field=models.TextField(verbose_name="事由"),
        ),
        migrations.AlterField(
            model_name="warninghistory",
            name="time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="時間"),
        ),
    ]
