# Generated by Django 5.2.5 on 2025-08-17 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0011_warninghistory_operator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warninghistory",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operated_warnings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人員",
            ),
        ),
    ]
