# Generated by Django 5.2.5 on 2025-08-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0012_alter_warninghistory_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="dmember",
            name="gen",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="屆別"
            ),
        ),
    ]
