# Generated by Django 5.2.6 on 2025-09-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0013_dmember_gen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dmember",
            name="discord_id",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Discord ID"
            ),
        ),
    ]
