# Generated by Django 5.2.7 on 2025-11-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0014_alter_dmember_discord_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="dmember",
            name="allow_login",
            field=models.BooleanField(default=True, verbose_name="允許登入"),
        ),
    ]
